# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

# Configuraci\u00f3n del servidor
server.port=8080

# Configuraci\u00f3n de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_empleados?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Juneam25

# Configuraci\u00f3n de JPA para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#  configuraci\u00f3n de H2
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# No ejecutar scripts automáticamente (prefiero control manual)
spring.sql.init.mode=never

# Configuraci\u00f3n de Thymeleaf (se mantiene igual)
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging (se mantiene igual)
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR